[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions."claude"]
  timeout = 26

[functions."analyzeurl"]
  timeout = 26
